version: '3'
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
  web:
    build: .
    image: planeat
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
    depends_on:
      - db