# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_weightmeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='unit',
            field=models.CharField(default='g', max_length=30),
        ),
    ]
